provider: tls
major-version: 5
makeTemplate: bridged
generate-nightly-test-workflow: true
providerDefaultBranch: main
team: ecosystem
license:
    ignore:
        - github.com/hashicorp/terraform-provider-tls/shim
pulumiConvert: 1
registryDocs: true
releaseVerification:
    nodejs: examples/private-key/ts
    python: examples/private-key/py
    dotnet: examples/private-key/dotnet
    go: examples/private-key/go
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
