provider: tls
major-version: 5
makeTemplate: bridged
generate-nightly-test-workflow: true
plugins:
  - name: aws
    version: "4.26.0"
javaGenVersion: "v0.9.7"
team: ecosystem
license:
  ignore:
    - github.com/hashicorp/terraform-provider-tls/shim
