provider: tls
major-version: 4
makeTemplate: bridged
# TODO: Enable this once our tls provider is updated with framework support
# generate-nightly-test-workflow: true
plugins:
  - name: aws
    version: "4.26.0"
javaGenVersion: "v0.9.7"
team: ecosystem
license:
  ignore:
    - github.com/terraform-providers/terraform-provider-tls/shim
