version: "2"
linters:
  enable:
  - errcheck
  - goconst
  - gosec
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - unconvert
formatters:
  enable:
  - gofmt
run:
  timeout: 20m
issues:
  exclude-files:
  - schema.go
  - pulumiManifest.go
