// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tls;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.tls.PrivateKeyArgs;
import com.pulumi.tls.Utilities;
import com.pulumi.tls.inputs.PrivateKeyState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="tls:index/privateKey:PrivateKey")
public class PrivateKey extends com.pulumi.resources.CustomResource {
    /**
     * Name of the algorithm to use when generating the private key. Currently-supported values are `RSA`, `ECDSA` and `ED25519`.
     * 
     */
    @Export(name="algorithm", refs={String.class}, tree="[0]")
    private Output<String> algorithm;

    /**
     * @return Name of the algorithm to use when generating the private key. Currently-supported values are `RSA`, `ECDSA` and `ED25519`.
     * 
     */
    public Output<String> algorithm() {
        return this.algorithm;
    }
    /**
     * When `algorithm` is `ECDSA`, the name of the elliptic curve to use. Currently-supported values are `P224`, `P256`, `P384` or `P521` (default: `P224`).
     * 
     */
    @Export(name="ecdsaCurve", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ecdsaCurve;

    /**
     * @return When `algorithm` is `ECDSA`, the name of the elliptic curve to use. Currently-supported values are `P224`, `P256`, `P384` or `P521` (default: `P224`).
     * 
     */
    public Output<Optional<String>> ecdsaCurve() {
        return Codegen.optional(this.ecdsaCurve);
    }
    /**
     * Private key data in [OpenSSH PEM (RFC 4716)](https://datatracker.ietf.org/doc/html/rfc4716) format.
     * 
     */
    @Export(name="privateKeyOpenssh", refs={String.class}, tree="[0]")
    private Output<String> privateKeyOpenssh;

    /**
     * @return Private key data in [OpenSSH PEM (RFC 4716)](https://datatracker.ietf.org/doc/html/rfc4716) format.
     * 
     */
    public Output<String> privateKeyOpenssh() {
        return this.privateKeyOpenssh;
    }
    /**
     * Private key data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
     * 
     */
    @Export(name="privateKeyPem", refs={String.class}, tree="[0]")
    private Output<String> privateKeyPem;

    /**
     * @return Private key data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
     * 
     */
    public Output<String> privateKeyPem() {
        return this.privateKeyPem;
    }
    /**
     * The fingerprint of the public key data in OpenSSH MD5 hash format, e.g. `aa:bb:cc:...`. Only available if the selected private key format is compatible, similarly to `public_key_openssh` and the ECDSA P224 limitations.
     * 
     */
    @Export(name="publicKeyFingerprintMd5", refs={String.class}, tree="[0]")
    private Output<String> publicKeyFingerprintMd5;

    /**
     * @return The fingerprint of the public key data in OpenSSH MD5 hash format, e.g. `aa:bb:cc:...`. Only available if the selected private key format is compatible, similarly to `public_key_openssh` and the ECDSA P224 limitations.
     * 
     */
    public Output<String> publicKeyFingerprintMd5() {
        return this.publicKeyFingerprintMd5;
    }
    /**
     * The fingerprint of the public key data in OpenSSH SHA256 hash format, e.g. `SHA256:...`. Only available if the selected private key format is compatible, similarly to `public_key_openssh` and the ECDSA P224 limitations.
     * 
     */
    @Export(name="publicKeyFingerprintSha256", refs={String.class}, tree="[0]")
    private Output<String> publicKeyFingerprintSha256;

    /**
     * @return The fingerprint of the public key data in OpenSSH SHA256 hash format, e.g. `SHA256:...`. Only available if the selected private key format is compatible, similarly to `public_key_openssh` and the ECDSA P224 limitations.
     * 
     */
    public Output<String> publicKeyFingerprintSha256() {
        return this.publicKeyFingerprintSha256;
    }
    /**
     * The public key data in &#34;Authorized Keys&#34;.
     * 
     */
    @Export(name="publicKeyOpenssh", refs={String.class}, tree="[0]")
    private Output<String> publicKeyOpenssh;

    /**
     * @return The public key data in &#34;Authorized Keys&#34;.
     * 
     */
    public Output<String> publicKeyOpenssh() {
        return this.publicKeyOpenssh;
    }
    /**
     * Public key data in PEM (RFC 1421).
     * 
     */
    @Export(name="publicKeyPem", refs={String.class}, tree="[0]")
    private Output<String> publicKeyPem;

    /**
     * @return Public key data in PEM (RFC 1421).
     * 
     */
    public Output<String> publicKeyPem() {
        return this.publicKeyPem;
    }
    /**
     * When `algorithm` is `RSA`, the size of the generated RSA key, in bits (default: `2048`).
     * 
     */
    @Export(name="rsaBits", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> rsaBits;

    /**
     * @return When `algorithm` is `RSA`, the size of the generated RSA key, in bits (default: `2048`).
     * 
     */
    public Output<Optional<Integer>> rsaBits() {
        return Codegen.optional(this.rsaBits);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public PrivateKey(String name) {
        this(name, PrivateKeyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public PrivateKey(String name, PrivateKeyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public PrivateKey(String name, PrivateKeyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("tls:index/privateKey:PrivateKey", name, args == null ? PrivateKeyArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private PrivateKey(String name, Output<String> id, @Nullable PrivateKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("tls:index/privateKey:PrivateKey", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .additionalSecretOutputs(List.of(
                "privateKeyOpenssh",
                "privateKeyPem"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static PrivateKey get(String name, Output<String> id, @Nullable PrivateKeyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new PrivateKey(name, id, state, options);
    }
}
