// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tls
{
    public static class GetPublicKey
    {
        /// <summary>
        /// Get a public key from a PEM-encoded private key.
        /// 
        /// Use this data source to get the public key from a [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) or [OpenSSH PEM (RFC 4716)](https://datatracker.ietf.org/doc/html/rfc4716) formatted private key, for use in other resources.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.IO;
        /// using Pulumi;
        /// using Tls = Pulumi.Tls;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ed25519_example = new Tls.PrivateKey("ed25519-example", new Tls.PrivateKeyArgs
        ///         {
        ///             Algorithm = "ED25519",
        ///         });
        ///         var privateKeyPem_example = Tls.GetPublicKey.Invoke(new Tls.GetPublicKeyInvokeArgs
        ///         {
        ///             PrivateKeyPem = ed25519_example.PrivateKeyPem,
        ///         });
        ///         var privateKeyOpenssh_example = Output.Create(Tls.GetPublicKey.InvokeAsync(new Tls.GetPublicKeyArgs
        ///         {
        ///             PrivateKeyOpenssh = File.ReadAllText("~/.ssh/id_rsa_rfc4716"),
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetPublicKeyResult> InvokeAsync(GetPublicKeyArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPublicKeyResult>("tls:index/getPublicKey:getPublicKey", args ?? new GetPublicKeyArgs(), options.WithDefaults());

        /// <summary>
        /// Get a public key from a PEM-encoded private key.
        /// 
        /// Use this data source to get the public key from a [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) or [OpenSSH PEM (RFC 4716)](https://datatracker.ietf.org/doc/html/rfc4716) formatted private key, for use in other resources.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.IO;
        /// using Pulumi;
        /// using Tls = Pulumi.Tls;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var ed25519_example = new Tls.PrivateKey("ed25519-example", new Tls.PrivateKeyArgs
        ///         {
        ///             Algorithm = "ED25519",
        ///         });
        ///         var privateKeyPem_example = Tls.GetPublicKey.Invoke(new Tls.GetPublicKeyInvokeArgs
        ///         {
        ///             PrivateKeyPem = ed25519_example.PrivateKeyPem,
        ///         });
        ///         var privateKeyOpenssh_example = Output.Create(Tls.GetPublicKey.InvokeAsync(new Tls.GetPublicKeyArgs
        ///         {
        ///             PrivateKeyOpenssh = File.ReadAllText("~/.ssh/id_rsa_rfc4716"),
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetPublicKeyResult> Invoke(GetPublicKeyInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetPublicKeyResult>("tls:index/getPublicKey:getPublicKey", args ?? new GetPublicKeyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPublicKeyArgs : Pulumi.InvokeArgs
    {
        [Input("privateKeyOpenssh")]
        public string? PrivateKeyOpenssh { get; set; }

        [Input("privateKeyPem")]
        public string? PrivateKeyPem { get; set; }

        public GetPublicKeyArgs()
        {
        }
    }

    public sealed class GetPublicKeyInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("privateKeyOpenssh")]
        public Input<string>? PrivateKeyOpenssh { get; set; }

        [Input("privateKeyPem")]
        public Input<string>? PrivateKeyPem { get; set; }

        public GetPublicKeyInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetPublicKeyResult
    {
        public readonly string Algorithm;
        public readonly string Id;
        public readonly string? PrivateKeyOpenssh;
        public readonly string? PrivateKeyPem;
        public readonly string PublicKeyFingerprintMd5;
        public readonly string PublicKeyFingerprintSha256;
        public readonly string PublicKeyOpenssh;
        public readonly string PublicKeyPem;

        [OutputConstructor]
        private GetPublicKeyResult(
            string algorithm,

            string id,

            string? privateKeyOpenssh,

            string? privateKeyPem,

            string publicKeyFingerprintMd5,

            string publicKeyFingerprintSha256,

            string publicKeyOpenssh,

            string publicKeyPem)
        {
            Algorithm = algorithm;
            Id = id;
            PrivateKeyOpenssh = privateKeyOpenssh;
            PrivateKeyPem = privateKeyPem;
            PublicKeyFingerprintMd5 = publicKeyFingerprintMd5;
            PublicKeyFingerprintSha256 = publicKeyFingerprintSha256;
            PublicKeyOpenssh = publicKeyOpenssh;
            PublicKeyPem = publicKeyPem;
        }
    }
}
