// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tls
{
    public partial class LocallySignedCert : Pulumi.CustomResource
    {
        /// <summary>
        /// List of keywords each describing a use that is permitted
        /// for the issued certificate. The valid keywords are listed below.
        /// </summary>
        [Output("allowedUses")]
        public Output<ImmutableArray<string>> AllowedUses { get; private set; } = null!;

        /// <summary>
        /// PEM-encoded certificate data for the CA.
        /// </summary>
        [Output("caCertPem")]
        public Output<string> CaCertPem { get; private set; } = null!;

        /// <summary>
        /// The name of the algorithm for the key provided
        /// in `ca_private_key_pem`.
        /// </summary>
        [Output("caKeyAlgorithm")]
        public Output<string> CaKeyAlgorithm { get; private set; } = null!;

        /// <summary>
        /// PEM-encoded private key data for the CA.
        /// This can be read from a separate file using the ``file`` interpolation
        /// function.
        /// </summary>
        [Output("caPrivateKeyPem")]
        public Output<string> CaPrivateKeyPem { get; private set; } = null!;

        /// <summary>
        /// The certificate data in PEM format.
        /// </summary>
        [Output("certPem")]
        public Output<string> CertPem { get; private set; } = null!;

        /// <summary>
        /// PEM-encoded request certificate data.
        /// </summary>
        [Output("certRequestPem")]
        public Output<string> CertRequestPem { get; private set; } = null!;

        /// <summary>
        /// Number of hours before the certificates expiry when a new certificate will be generated
        /// </summary>
        [Output("earlyRenewalHours")]
        public Output<int?> EarlyRenewalHours { get; private set; } = null!;

        /// <summary>
        /// Boolean controlling whether the CA flag will be set in the
        /// generated certificate. Defaults to `false`, meaning that the certificate does not represent
        /// a certificate authority.
        /// </summary>
        [Output("isCaCertificate")]
        public Output<bool?> IsCaCertificate { get; private set; } = null!;

        [Output("readyForRenewal")]
        public Output<bool> ReadyForRenewal { get; private set; } = null!;

        /// <summary>
        /// If `true`, the certificate will include
        /// the subject key identifier. Defaults to `false`, in which case the subject
        /// key identifier is not set at all.
        /// </summary>
        [Output("setSubjectKeyId")]
        public Output<bool?> SetSubjectKeyId { get; private set; } = null!;

        /// <summary>
        /// The time until which the certificate is invalid, as an
        /// [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Output("validityEndTime")]
        public Output<string> ValidityEndTime { get; private set; } = null!;

        /// <summary>
        /// The number of hours after initial issuing that the
        /// certificate will become invalid.
        /// </summary>
        [Output("validityPeriodHours")]
        public Output<int> ValidityPeriodHours { get; private set; } = null!;

        /// <summary>
        /// The time after which the certificate is valid, as an
        /// [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Output("validityStartTime")]
        public Output<string> ValidityStartTime { get; private set; } = null!;


        /// <summary>
        /// Create a LocallySignedCert resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LocallySignedCert(string name, LocallySignedCertArgs args, CustomResourceOptions? options = null)
            : base("tls:index/locallySignedCert:LocallySignedCert", name, args ?? ResourceArgs.Empty, MakeResourceOptions(options, ""))
        {
        }

        private LocallySignedCert(string name, Input<string> id, LocallySignedCertState? state = null, CustomResourceOptions? options = null)
            : base("tls:index/locallySignedCert:LocallySignedCert", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LocallySignedCert resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LocallySignedCert Get(string name, Input<string> id, LocallySignedCertState? state = null, CustomResourceOptions? options = null)
        {
            return new LocallySignedCert(name, id, state, options);
        }
    }

    public sealed class LocallySignedCertArgs : Pulumi.ResourceArgs
    {
        [Input("allowedUses", required: true)]
        private InputList<string>? _allowedUses;

        /// <summary>
        /// List of keywords each describing a use that is permitted
        /// for the issued certificate. The valid keywords are listed below.
        /// </summary>
        public InputList<string> AllowedUses
        {
            get => _allowedUses ?? (_allowedUses = new InputList<string>());
            set => _allowedUses = value;
        }

        /// <summary>
        /// PEM-encoded certificate data for the CA.
        /// </summary>
        [Input("caCertPem", required: true)]
        public Input<string> CaCertPem { get; set; } = null!;

        /// <summary>
        /// The name of the algorithm for the key provided
        /// in `ca_private_key_pem`.
        /// </summary>
        [Input("caKeyAlgorithm", required: true)]
        public Input<string> CaKeyAlgorithm { get; set; } = null!;

        /// <summary>
        /// PEM-encoded private key data for the CA.
        /// This can be read from a separate file using the ``file`` interpolation
        /// function.
        /// </summary>
        [Input("caPrivateKeyPem", required: true)]
        public Input<string> CaPrivateKeyPem { get; set; } = null!;

        /// <summary>
        /// PEM-encoded request certificate data.
        /// </summary>
        [Input("certRequestPem", required: true)]
        public Input<string> CertRequestPem { get; set; } = null!;

        /// <summary>
        /// Number of hours before the certificates expiry when a new certificate will be generated
        /// </summary>
        [Input("earlyRenewalHours")]
        public Input<int>? EarlyRenewalHours { get; set; }

        /// <summary>
        /// Boolean controlling whether the CA flag will be set in the
        /// generated certificate. Defaults to `false`, meaning that the certificate does not represent
        /// a certificate authority.
        /// </summary>
        [Input("isCaCertificate")]
        public Input<bool>? IsCaCertificate { get; set; }

        /// <summary>
        /// If `true`, the certificate will include
        /// the subject key identifier. Defaults to `false`, in which case the subject
        /// key identifier is not set at all.
        /// </summary>
        [Input("setSubjectKeyId")]
        public Input<bool>? SetSubjectKeyId { get; set; }

        /// <summary>
        /// The number of hours after initial issuing that the
        /// certificate will become invalid.
        /// </summary>
        [Input("validityPeriodHours", required: true)]
        public Input<int> ValidityPeriodHours { get; set; } = null!;

        public LocallySignedCertArgs()
        {
        }
    }

    public sealed class LocallySignedCertState : Pulumi.ResourceArgs
    {
        [Input("allowedUses")]
        private InputList<string>? _allowedUses;

        /// <summary>
        /// List of keywords each describing a use that is permitted
        /// for the issued certificate. The valid keywords are listed below.
        /// </summary>
        public InputList<string> AllowedUses
        {
            get => _allowedUses ?? (_allowedUses = new InputList<string>());
            set => _allowedUses = value;
        }

        /// <summary>
        /// PEM-encoded certificate data for the CA.
        /// </summary>
        [Input("caCertPem")]
        public Input<string>? CaCertPem { get; set; }

        /// <summary>
        /// The name of the algorithm for the key provided
        /// in `ca_private_key_pem`.
        /// </summary>
        [Input("caKeyAlgorithm")]
        public Input<string>? CaKeyAlgorithm { get; set; }

        /// <summary>
        /// PEM-encoded private key data for the CA.
        /// This can be read from a separate file using the ``file`` interpolation
        /// function.
        /// </summary>
        [Input("caPrivateKeyPem")]
        public Input<string>? CaPrivateKeyPem { get; set; }

        /// <summary>
        /// The certificate data in PEM format.
        /// </summary>
        [Input("certPem")]
        public Input<string>? CertPem { get; set; }

        /// <summary>
        /// PEM-encoded request certificate data.
        /// </summary>
        [Input("certRequestPem")]
        public Input<string>? CertRequestPem { get; set; }

        /// <summary>
        /// Number of hours before the certificates expiry when a new certificate will be generated
        /// </summary>
        [Input("earlyRenewalHours")]
        public Input<int>? EarlyRenewalHours { get; set; }

        /// <summary>
        /// Boolean controlling whether the CA flag will be set in the
        /// generated certificate. Defaults to `false`, meaning that the certificate does not represent
        /// a certificate authority.
        /// </summary>
        [Input("isCaCertificate")]
        public Input<bool>? IsCaCertificate { get; set; }

        [Input("readyForRenewal")]
        public Input<bool>? ReadyForRenewal { get; set; }

        /// <summary>
        /// If `true`, the certificate will include
        /// the subject key identifier. Defaults to `false`, in which case the subject
        /// key identifier is not set at all.
        /// </summary>
        [Input("setSubjectKeyId")]
        public Input<bool>? SetSubjectKeyId { get; set; }

        /// <summary>
        /// The time until which the certificate is invalid, as an
        /// [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Input("validityEndTime")]
        public Input<string>? ValidityEndTime { get; set; }

        /// <summary>
        /// The number of hours after initial issuing that the
        /// certificate will become invalid.
        /// </summary>
        [Input("validityPeriodHours")]
        public Input<int>? ValidityPeriodHours { get; set; }

        /// <summary>
        /// The time after which the certificate is valid, as an
        /// [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Input("validityStartTime")]
        public Input<string>? ValidityStartTime { get; set; }

        public LocallySignedCertState()
        {
        }
    }
}
