// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Tls
{
    [TlsResourceType("tls:index/locallySignedCert:LocallySignedCert")]
    public partial class LocallySignedCert : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of key usages allowed for the issued certificate. Values are defined in [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) and combine flags defined by both [Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.3) and [Extended Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12). Accepted values: `AnyExtended`, `CertSigning`, `ClientAuth`, `CodeSigning`, `ContentCommitment`, `CrlSigning`, `DataEncipherment`, `DecipherOnly`, `DigitalSignature`, `EmailProtection`, `EncipherOnly`, `IpsecEndSystem`, `IpsecTunnel`, `IpsecUser`, `KeyAgreement`, `KeyEncipherment`, `MicrosoftCommercialCodeSigning`, `MicrosoftKernelCodeSigning`, `MicrosoftServerGatedCrypto`, `NetscapeServerGatedCrypto`, `OcspSigning`, `ServerAuth`, `Timestamping`.
        /// </summary>
        [Output("allowedUses")]
        public Output<ImmutableArray<string>> AllowedUses { get; private set; } = null!;

        /// <summary>
        /// Certificate data of the Certificate Authority (CA) in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Output("caCertPem")]
        public Output<string> CaCertPem { get; private set; } = null!;

        /// <summary>
        /// Name of the algorithm used when generating the private key provided in `CaPrivateKeyPem`.
        /// </summary>
        [Output("caKeyAlgorithm")]
        public Output<string> CaKeyAlgorithm { get; private set; } = null!;

        /// <summary>
        /// Private key of the Certificate Authority (CA) used to sign the certificate, in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Output("caPrivateKeyPem")]
        public Output<string> CaPrivateKeyPem { get; private set; } = null!;

        /// <summary>
        /// Certificate data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format. **NOTE**: the [underlying](https://pkg.go.dev/encoding/pem#Encode) [libraries](https://pkg.go.dev/golang.org/x/crypto/ssh#MarshalAuthorizedKey) that generate this value append a `\n` at the end of the PEM. In case this disrupts your use case, we recommend using `trimspace()`.
        /// </summary>
        [Output("certPem")]
        public Output<string> CertPem { get; private set; } = null!;

        /// <summary>
        /// Certificate request data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Output("certRequestPem")]
        public Output<string> CertRequestPem { get; private set; } = null!;

        [Output("earlyRenewalHours")]
        public Output<int> EarlyRenewalHours { get; private set; } = null!;

        /// <summary>
        /// Is the generated certificate representing a Certificate Authority (CA) (default: `False`).
        /// </summary>
        [Output("isCaCertificate")]
        public Output<bool> IsCaCertificate { get; private set; } = null!;

        /// <summary>
        /// Maximum number of intermediate certificates that may follow this certificate in a valid certification path. If `IsCaCertificate` is `False`, this value is ignored. (default: `-1`)
        /// </summary>
        [Output("maxPathLength")]
        public Output<int> MaxPathLength { get; private set; } = null!;

        /// <summary>
        /// Is the certificate either expired (i.e. beyond the `ValidityPeriodHours`) or ready for an early renewal (i.e. within the `EarlyRenewalHours`)?
        /// </summary>
        [Output("readyForRenewal")]
        public Output<bool> ReadyForRenewal { get; private set; } = null!;

        /// <summary>
        /// Should the generated certificate include a [subject key identifier](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.2) (default: `False`).
        /// </summary>
        [Output("setSubjectKeyId")]
        public Output<bool> SetSubjectKeyId { get; private set; } = null!;

        /// <summary>
        /// The time until which the certificate is invalid, expressed as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Output("validityEndTime")]
        public Output<string> ValidityEndTime { get; private set; } = null!;

        /// <summary>
        /// Number of hours, after initial issuing, that the certificate will remain valid for.
        /// </summary>
        [Output("validityPeriodHours")]
        public Output<int> ValidityPeriodHours { get; private set; } = null!;

        /// <summary>
        /// The time after which the certificate is valid, expressed as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Output("validityStartTime")]
        public Output<string> ValidityStartTime { get; private set; } = null!;


        /// <summary>
        /// Create a LocallySignedCert resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public LocallySignedCert(string name, LocallySignedCertArgs args, CustomResourceOptions? options = null)
            : base("tls:index/locallySignedCert:LocallySignedCert", name, args ?? new LocallySignedCertArgs(), MakeResourceOptions(options, ""))
        {
        }

        private LocallySignedCert(string name, Input<string> id, LocallySignedCertState? state = null, CustomResourceOptions? options = null)
            : base("tls:index/locallySignedCert:LocallySignedCert", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "caPrivateKeyPem",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing LocallySignedCert resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static LocallySignedCert Get(string name, Input<string> id, LocallySignedCertState? state = null, CustomResourceOptions? options = null)
        {
            return new LocallySignedCert(name, id, state, options);
        }
    }

    public sealed class LocallySignedCertArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowedUses", required: true)]
        private InputList<string>? _allowedUses;

        /// <summary>
        /// List of key usages allowed for the issued certificate. Values are defined in [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) and combine flags defined by both [Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.3) and [Extended Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12). Accepted values: `AnyExtended`, `CertSigning`, `ClientAuth`, `CodeSigning`, `ContentCommitment`, `CrlSigning`, `DataEncipherment`, `DecipherOnly`, `DigitalSignature`, `EmailProtection`, `EncipherOnly`, `IpsecEndSystem`, `IpsecTunnel`, `IpsecUser`, `KeyAgreement`, `KeyEncipherment`, `MicrosoftCommercialCodeSigning`, `MicrosoftKernelCodeSigning`, `MicrosoftServerGatedCrypto`, `NetscapeServerGatedCrypto`, `OcspSigning`, `ServerAuth`, `Timestamping`.
        /// </summary>
        public InputList<string> AllowedUses
        {
            get => _allowedUses ?? (_allowedUses = new InputList<string>());
            set => _allowedUses = value;
        }

        /// <summary>
        /// Certificate data of the Certificate Authority (CA) in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Input("caCertPem", required: true)]
        public Input<string> CaCertPem { get; set; } = null!;

        [Input("caPrivateKeyPem", required: true)]
        private Input<string>? _caPrivateKeyPem;

        /// <summary>
        /// Private key of the Certificate Authority (CA) used to sign the certificate, in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        public Input<string>? CaPrivateKeyPem
        {
            get => _caPrivateKeyPem;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _caPrivateKeyPem = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Certificate request data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Input("certRequestPem", required: true)]
        public Input<string> CertRequestPem { get; set; } = null!;

        [Input("earlyRenewalHours")]
        public Input<int>? EarlyRenewalHours { get; set; }

        /// <summary>
        /// Is the generated certificate representing a Certificate Authority (CA) (default: `False`).
        /// </summary>
        [Input("isCaCertificate")]
        public Input<bool>? IsCaCertificate { get; set; }

        /// <summary>
        /// Maximum number of intermediate certificates that may follow this certificate in a valid certification path. If `IsCaCertificate` is `False`, this value is ignored. (default: `-1`)
        /// </summary>
        [Input("maxPathLength")]
        public Input<int>? MaxPathLength { get; set; }

        /// <summary>
        /// Should the generated certificate include a [subject key identifier](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.2) (default: `False`).
        /// </summary>
        [Input("setSubjectKeyId")]
        public Input<bool>? SetSubjectKeyId { get; set; }

        /// <summary>
        /// Number of hours, after initial issuing, that the certificate will remain valid for.
        /// </summary>
        [Input("validityPeriodHours", required: true)]
        public Input<int> ValidityPeriodHours { get; set; } = null!;

        public LocallySignedCertArgs()
        {
        }
        public static new LocallySignedCertArgs Empty => new LocallySignedCertArgs();
    }

    public sealed class LocallySignedCertState : global::Pulumi.ResourceArgs
    {
        [Input("allowedUses")]
        private InputList<string>? _allowedUses;

        /// <summary>
        /// List of key usages allowed for the issued certificate. Values are defined in [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) and combine flags defined by both [Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.3) and [Extended Key Usages](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.12). Accepted values: `AnyExtended`, `CertSigning`, `ClientAuth`, `CodeSigning`, `ContentCommitment`, `CrlSigning`, `DataEncipherment`, `DecipherOnly`, `DigitalSignature`, `EmailProtection`, `EncipherOnly`, `IpsecEndSystem`, `IpsecTunnel`, `IpsecUser`, `KeyAgreement`, `KeyEncipherment`, `MicrosoftCommercialCodeSigning`, `MicrosoftKernelCodeSigning`, `MicrosoftServerGatedCrypto`, `NetscapeServerGatedCrypto`, `OcspSigning`, `ServerAuth`, `Timestamping`.
        /// </summary>
        public InputList<string> AllowedUses
        {
            get => _allowedUses ?? (_allowedUses = new InputList<string>());
            set => _allowedUses = value;
        }

        /// <summary>
        /// Certificate data of the Certificate Authority (CA) in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Input("caCertPem")]
        public Input<string>? CaCertPem { get; set; }

        /// <summary>
        /// Name of the algorithm used when generating the private key provided in `CaPrivateKeyPem`.
        /// </summary>
        [Input("caKeyAlgorithm")]
        public Input<string>? CaKeyAlgorithm { get; set; }

        [Input("caPrivateKeyPem")]
        private Input<string>? _caPrivateKeyPem;

        /// <summary>
        /// Private key of the Certificate Authority (CA) used to sign the certificate, in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        public Input<string>? CaPrivateKeyPem
        {
            get => _caPrivateKeyPem;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _caPrivateKeyPem = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Certificate data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format. **NOTE**: the [underlying](https://pkg.go.dev/encoding/pem#Encode) [libraries](https://pkg.go.dev/golang.org/x/crypto/ssh#MarshalAuthorizedKey) that generate this value append a `\n` at the end of the PEM. In case this disrupts your use case, we recommend using `trimspace()`.
        /// </summary>
        [Input("certPem")]
        public Input<string>? CertPem { get; set; }

        /// <summary>
        /// Certificate request data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format.
        /// </summary>
        [Input("certRequestPem")]
        public Input<string>? CertRequestPem { get; set; }

        [Input("earlyRenewalHours")]
        public Input<int>? EarlyRenewalHours { get; set; }

        /// <summary>
        /// Is the generated certificate representing a Certificate Authority (CA) (default: `False`).
        /// </summary>
        [Input("isCaCertificate")]
        public Input<bool>? IsCaCertificate { get; set; }

        /// <summary>
        /// Maximum number of intermediate certificates that may follow this certificate in a valid certification path. If `IsCaCertificate` is `False`, this value is ignored. (default: `-1`)
        /// </summary>
        [Input("maxPathLength")]
        public Input<int>? MaxPathLength { get; set; }

        /// <summary>
        /// Is the certificate either expired (i.e. beyond the `ValidityPeriodHours`) or ready for an early renewal (i.e. within the `EarlyRenewalHours`)?
        /// </summary>
        [Input("readyForRenewal")]
        public Input<bool>? ReadyForRenewal { get; set; }

        /// <summary>
        /// Should the generated certificate include a [subject key identifier](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.2) (default: `False`).
        /// </summary>
        [Input("setSubjectKeyId")]
        public Input<bool>? SetSubjectKeyId { get; set; }

        /// <summary>
        /// The time until which the certificate is invalid, expressed as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Input("validityEndTime")]
        public Input<string>? ValidityEndTime { get; set; }

        /// <summary>
        /// Number of hours, after initial issuing, that the certificate will remain valid for.
        /// </summary>
        [Input("validityPeriodHours")]
        public Input<int>? ValidityPeriodHours { get; set; }

        /// <summary>
        /// The time after which the certificate is valid, expressed as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
        /// </summary>
        [Input("validityStartTime")]
        public Input<string>? ValidityStartTime { get; set; }

        public LocallySignedCertState()
        {
        }
        public static new LocallySignedCertState Empty => new LocallySignedCertState();
    }
}
