// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.tls.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPublicKeyArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPublicKeyArgs Empty = new GetPublicKeyArgs();

    @Import(name="privateKeyOpenssh")
    private @Nullable Output<String> privateKeyOpenssh;

    public Optional<Output<String>> privateKeyOpenssh() {
        return Optional.ofNullable(this.privateKeyOpenssh);
    }

    @Import(name="privateKeyPem")
    private @Nullable Output<String> privateKeyPem;

    public Optional<Output<String>> privateKeyPem() {
        return Optional.ofNullable(this.privateKeyPem);
    }

    private GetPublicKeyArgs() {}

    private GetPublicKeyArgs(GetPublicKeyArgs $) {
        this.privateKeyOpenssh = $.privateKeyOpenssh;
        this.privateKeyPem = $.privateKeyPem;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPublicKeyArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPublicKeyArgs $;

        public Builder() {
            $ = new GetPublicKeyArgs();
        }

        public Builder(GetPublicKeyArgs defaults) {
            $ = new GetPublicKeyArgs(Objects.requireNonNull(defaults));
        }

        public Builder privateKeyOpenssh(@Nullable Output<String> privateKeyOpenssh) {
            $.privateKeyOpenssh = privateKeyOpenssh;
            return this;
        }

        public Builder privateKeyOpenssh(String privateKeyOpenssh) {
            return privateKeyOpenssh(Output.of(privateKeyOpenssh));
        }

        public Builder privateKeyPem(@Nullable Output<String> privateKeyPem) {
            $.privateKeyPem = privateKeyPem;
            return this;
        }

        public Builder privateKeyPem(String privateKeyPem) {
            return privateKeyPem(Output.of(privateKeyPem));
        }

        public GetPublicKeyArgs build() {
            return $;
        }
    }

}
