// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package tls

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCertificate(ctx *pulumi.Context, args *GetCertificateArgs, opts ...pulumi.InvokeOption) (*GetCertificateResult, error) {
	var rv GetCertificateResult
	err := ctx.Invoke("tls:index/getCertificate:getCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCertificate.
type GetCertificateArgs struct {
	Url         string `pulumi:"url"`
	VerifyChain *bool  `pulumi:"verifyChain"`
}

// A collection of values returned by getCertificate.
type GetCertificateResult struct {
	Certificates []GetCertificateCertificate `pulumi:"certificates"`
	Id           string                      `pulumi:"id"`
	Url          string                      `pulumi:"url"`
	VerifyChain  *bool                       `pulumi:"verifyChain"`
}

func GetCertificateOutput(ctx *pulumi.Context, args GetCertificateOutputArgs, opts ...pulumi.InvokeOption) GetCertificateResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetCertificateResult, error) {
			args := v.(GetCertificateArgs)
			r, err := GetCertificate(ctx, &args, opts...)
			var s GetCertificateResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetCertificateResultOutput)
}

// A collection of arguments for invoking getCertificate.
type GetCertificateOutputArgs struct {
	Url         pulumi.StringInput  `pulumi:"url"`
	VerifyChain pulumi.BoolPtrInput `pulumi:"verifyChain"`
}

func (GetCertificateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCertificateArgs)(nil)).Elem()
}

// A collection of values returned by getCertificate.
type GetCertificateResultOutput struct{ *pulumi.OutputState }

func (GetCertificateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetCertificateResult)(nil)).Elem()
}

func (o GetCertificateResultOutput) ToGetCertificateResultOutput() GetCertificateResultOutput {
	return o
}

func (o GetCertificateResultOutput) ToGetCertificateResultOutputWithContext(ctx context.Context) GetCertificateResultOutput {
	return o
}

func (o GetCertificateResultOutput) Certificates() GetCertificateCertificateArrayOutput {
	return o.ApplyT(func(v GetCertificateResult) []GetCertificateCertificate { return v.Certificates }).(GetCertificateCertificateArrayOutput)
}

func (o GetCertificateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetCertificateResultOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v GetCertificateResult) string { return v.Url }).(pulumi.StringOutput)
}

func (o GetCertificateResultOutput) VerifyChain() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetCertificateResult) *bool { return v.VerifyChain }).(pulumi.BoolPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetCertificateResultOutput{})
}
