// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CertRequestSubject {
    /**
     * Distinguished name: `CN`
     */
    commonName?: string;
    /**
     * Distinguished name: `C`
     */
    country?: string;
    /**
     * ASN.1 Object Identifier (OID): `1.2.840.113549.1.9.1`
     */
    emailAddress?: string;
    /**
     * Distinguished name: `L`
     */
    locality?: string;
    /**
     * Distinguished name: `O`
     */
    organization?: string;
    /**
     * Distinguished name: `OU`
     */
    organizationalUnit?: string;
    /**
     * Distinguished name: `PC`
     */
    postalCode?: string;
    /**
     * Distinguished name: `ST`
     */
    province?: string;
    /**
     * Distinguished name: `SERIALNUMBER`
     */
    serialNumber?: string;
    /**
     * Distinguished name: `STREET`
     */
    streetAddresses?: string[];
}

export interface GetCertificateCertificate {
    /**
     * Certificate data in [PEM (RFC 1421)](https://datatracker.ietf.org/doc/html/rfc1421) format. **NOTE**: the [underlying](https://pkg.go.dev/encoding/pem#Encode) [libraries](https://pkg.go.dev/golang.org/x/crypto/ssh#MarshalAuthorizedKey) that generate this value append a `\n` at the end of the PEM. In case this disrupts your use case, we recommend using `trimspace()`.
     */
    certPem: string;
    /**
     * `true` if the certificate is of a CA (Certificate Authority).
     */
    isCa: boolean;
    /**
     * Who verified and signed the certificate, roughly following [RFC2253](https://tools.ietf.org/html/rfc2253).
     */
    issuer: string;
    /**
     * The maximum number of intermediate certificates that can follow this certificate in a valid certification path. If `isCa` is `false`, this value is `-1`.
     */
    maxPathLength: number;
    /**
     * The time until which the certificate is invalid, as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
     */
    notAfter: string;
    /**
     * The time after which the certificate is valid, as an [RFC3339](https://tools.ietf.org/html/rfc3339) timestamp.
     */
    notBefore: string;
    /**
     * The key algorithm used to create the certificate.
     */
    publicKeyAlgorithm: string;
    /**
     * Number that uniquely identifies the certificate with the CA's system.
     * The `format` function can be used to convert this *base 10* number into other bases, such as hex.
     */
    serialNumber: string;
    /**
     * The SHA1 fingerprint of the public key of the certificate.
     */
    sha1Fingerprint: string;
    /**
     * The algorithm used to sign the certificate.
     */
    signatureAlgorithm: string;
    /**
     * The entity the certificate belongs to, roughly following [RFC2253](https://tools.ietf.org/html/rfc2253).
     */
    subject: string;
    /**
     * The version the certificate is in.
     */
    version: number;
}

export interface SelfSignedCertSubject {
    /**
     * Distinguished name: `CN`
     */
    commonName?: string;
    /**
     * Distinguished name: `C`
     */
    country?: string;
    /**
     * ASN.1 Object Identifier (OID): `1.2.840.113549.1.9.1`
     */
    emailAddress?: string;
    /**
     * Distinguished name: `L`
     */
    locality?: string;
    /**
     * Distinguished name: `O`
     */
    organization?: string;
    /**
     * Distinguished name: `OU`
     */
    organizationalUnit?: string;
    /**
     * Distinguished name: `PC`
     */
    postalCode?: string;
    /**
     * Distinguished name: `ST`
     */
    province?: string;
    /**
     * Distinguished name: `SERIALNUMBER`
     */
    serialNumber?: string;
    /**
     * Distinguished name: `STREET`
     */
    streetAddresses?: string[];
}

export namespace config {
    export interface Proxy {
        /**
         * When `true` the provider will discover the proxy configuration from environment variables. This is based upon [`http.ProxyFromEnvironment`](https://pkg.go.dev/net/http#ProxyFromEnvironment) and it supports the same environment variables (default: `true`).
         */
        fromEnv?: boolean;
        /**
         * Password used for Basic authentication against the Proxy.
         */
        password?: string;
        /**
         * URL used to connect to the Proxy. Accepted schemes are: `http`, `https`, `socks5`.
         */
        url?: string;
        /**
         * Username (or Token) used for Basic authentication against the Proxy.
         */
        username?: string;
    }

}
