// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CertRequestSubject {
    commonName?: string;
    country?: string;
    locality?: string;
    organization?: string;
    organizationalUnit?: string;
    postalCode?: string;
    province?: string;
    serialNumber?: string;
    streetAddresses?: string[];
}

export interface SelfSignedCertSubject {
    commonName?: string;
    country?: string;
    locality?: string;
    organization?: string;
    organizationalUnit?: string;
    postalCode?: string;
    province?: string;
    serialNumber?: string;
    streetAddresses?: string[];
}
