name: Upgrade Java
on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          The version of pulumi/pulumi-java to upgrade to, without the 'v' prefix
        required: true
        type: string
      upgradeProviderVersion:
        description: |
          Version of upgrade-provider to use. This must be a valid git reference in the pulumi/upgrade-provider repo. Defaults to "main"

          See https://go.dev/ref/mod#versions for valid versions. E.g. "v0.1.0", "main", "da25dec".
        default: main
        type: string
  # schedule:
  #   # 3 AM UTC ~ 8 PM PDT / 7 PM PST daily. Time chosen to run during off hours.
  #   - cron: 0 3 * * *

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  GH_TOKEN: ${{ secrets.PULUMI_PROVIDER_AUTOMATION_TOKEN || secrets.PULUMI_BOT_TOKEN || secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  upgrade_java:
    name: upgrade-java
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Persist credentials so upgrade-provider can push a new branch.
          persist-credentials: true

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: pulumictl, pulumicli, go

      - name: Install upgrade-provider
        run: go install github.com/pulumi/upgrade-provider@${{ inputs.upgradeProviderVersion || 'main' }}
        shell: bash

      - name: "Set up git identity"
        run: |
          git config --global user.name 'bot@pulumi.com'
          git config --global user.email 'bot@pulumi.com'
        shell: bash

      - name: Upgrade Java
        shell: bash
        id: upgrade_provider
        env:
          V: ${{inputs.version}}
        run: |
          cd provider
          upgrade-provider pulumi/pulumi-tls --kind=java --java-version="$V"
